//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACOMPAÑANTE
    {
        public ACOMPAÑANTE()
        {
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public string DNI_ACOMPANANTE { get; set; }
        public string NOMBRE_COMPLETO { get; set; }
        public string EXTRANJERO { get; set; }
        public string CORREO { get; set; }
        public Nullable<int> TELEFONO { get; set; }
    
        public virtual ICollection<RESERVA> RESERVA { get; set; }
    }
}
