//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clases
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PryTR : DbContext
    {
        public PryTR()
            : base("name=PryTR")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACOMPAÑANTE> ACOMPAÑANTE { get; set; }
        public DbSet<CIUDAD> CIUDAD { get; set; }
        public DbSet<CONDUCTOR> CONDUCTOR { get; set; }
        public DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public DbSet<FOTO_DEPT> FOTO_DEPT { get; set; }
        public DbSet<INVENTARIO> INVENTARIO { get; set; }
        public DbSet<MANTENCION> MANTENCION { get; set; }
        public DbSet<MULTA> MULTA { get; set; }
        public DbSet<RESERVA> RESERVA { get; set; }
        public DbSet<ROL> ROL { get; set; }
        public DbSet<SERVICIO_EXTRA> SERVICIO_EXTRA { get; set; }
        public DbSet<SERVICIO_TOURS> SERVICIO_TOURS { get; set; }
        public DbSet<SERVICIO_TRANSPORTE> SERVICIO_TRANSPORTE { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VEHICULO> VEHICULO { get; set; }
        public DbSet<ZONA_TOUR> ZONA_TOUR { get; set; }
        public DbSet<CHECKLIST> CHECKLIST { get; set; }
        public DbSet<RESERVA_SERVICIO> RESERVA_SERVICIO { get; set; }
        public DbSet<RESERVA_TOUR> RESERVA_TOUR { get; set; }
        public DbSet<RESERVA_TRANSPORTE> RESERVA_TRANSPORTE { get; set; }
    }
}
