//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDUCTOR
    {
        public CONDUCTOR()
        {
            this.SERVICIO_TRANSPORTE = new HashSet<SERVICIO_TRANSPORTE>();
            this.VEHICULO = new HashSet<VEHICULO>();
        }
    
        public string DNI { get; set; }
        public string NOMBRE { get; set; }
        public string EXTRANJERO { get; set; }
    
        public virtual ICollection<SERVICIO_TRANSPORTE> SERVICIO_TRANSPORTE { get; set; }
        public virtual ICollection<VEHICULO> VEHICULO { get; set; }
    }
}
