//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPARTAMENTO
    {
        public DEPARTAMENTO()
        {
            this.FOTO_DEPT = new HashSet<FOTO_DEPT>();
            this.INVENTARIO = new HashSet<INVENTARIO>();
            this.MANTENCION = new HashSet<MANTENCION>();
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public short ID_DEPARTAMENTO { get; set; }
        public string DIRECCION { get; set; }
        public short CANT_BANIOS { get; set; }
        public short CANT_DORMITORIOS { get; set; }
        public int PRECIO_DIARIO { get; set; }
        public string DESCRIPCION { get; set; }
        public string ACTIVADO { get; set; }
        public string CONDICIONES_USO { get; set; }
        public short PORCENTAJE { get; set; }
        public short CIUDAD_ID_CIUDAD { get; set; }
        public string INTERNET { get; set; }
        public string CALEFACCION { get; set; }
    
        public virtual CIUDAD CIUDAD { get; set; }
        public virtual ICollection<FOTO_DEPT> FOTO_DEPT { get; set; }
        public virtual ICollection<INVENTARIO> INVENTARIO { get; set; }
        public virtual ICollection<MANTENCION> MANTENCION { get; set; }
        public virtual ICollection<RESERVA> RESERVA { get; set; }
    }
}
