//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTARIO
    {
        public INVENTARIO()
        {
            this.CHECKLIST = new HashSet<CHECKLIST>();
        }
    
        public string ID_INVENTARIO { get; set; }
        public string NOMBRE { get; set; }
        public int PRECIO { get; set; }
        public string IMPORTANTE { get; set; }
        public string ESTADO { get; set; }
        public short DEPARTAMENTO_ID_DEPARTAMENTO { get; set; }
    
        public virtual DEPARTAMENTO DEPARTAMENTO { get; set; }
        public virtual ICollection<CHECKLIST> CHECKLIST { get; set; }
    }
}
