//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO_TRANSPORTE
    {
        public SERVICIO_TRANSPORTE()
        {
            this.RESERVA_TRANSPORTE = new HashSet<RESERVA_TRANSPORTE>();
        }
    
        public short ID_TRANSPORTE { get; set; }
        public string LUGAR { get; set; }
        public string HORA_COMIENZO { get; set; }
        public string HORA_TERMINO { get; set; }
        public System.DateTime FECHA { get; set; }
        public int PRECIO_ACTUAL { get; set; }
        public string CONDUCTOR_DNI { get; set; }
    
        public virtual CONDUCTOR CONDUCTOR { get; set; }
        public virtual ICollection<RESERVA_TRANSPORTE> RESERVA_TRANSPORTE { get; set; }
    }
}
