//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clases
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO_EXTRA
    {
        public SERVICIO_EXTRA()
        {
            this.RESERVA_SERVICIO = new HashSet<RESERVA_SERVICIO>();
        }
    
        public short ID_SERVICIO_EXTRA { get; set; }
        public string NOMBRE_SERVICIO_EX { get; set; }
        public int PRECIO_ACTUAL { get; set; }
    
        public virtual ICollection<RESERVA_SERVICIO> RESERVA_SERVICIO { get; set; }
    }
}
