//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectorOracle
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ATEntities : DbContext
    {
        public ATEntities()
            : base("name=ATEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACOMPANIANTE> ACOMPANIANTE { get; set; }
        public DbSet<CHECKLIST> CHECKLIST { get; set; }
        public DbSet<CIUDAD> CIUDAD { get; set; }
        public DbSet<CONDUCTOR> CONDUCTOR { get; set; }
        public DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public DbSet<FOTO_DEPT> FOTO_DEPT { get; set; }
        public DbSet<INVENTARIO> INVENTARIO { get; set; }
        public DbSet<MANTENCION> MANTENCION { get; set; }
        public DbSet<MULTA> MULTA { get; set; }
        public DbSet<PARAMETROS> PARAMETROS { get; set; }
        public DbSet<REPARACION> REPARACION { get; set; }
        public DbSet<RESERVA> RESERVA { get; set; }
        public DbSet<RESERVA_SERVICIO> RESERVA_SERVICIO { get; set; }
        public DbSet<RESERVA_TOUR> RESERVA_TOUR { get; set; }
        public DbSet<RESERVA_TRANSPORTE> RESERVA_TRANSPORTE { get; set; }
        public DbSet<ROL> ROL { get; set; }
        public DbSet<SERVICIO_EXTRA> SERVICIO_EXTRA { get; set; }
        public DbSet<SERVICIO_TOURS> SERVICIO_TOURS { get; set; }
        public DbSet<SERVICIO_TRANSPORTE> SERVICIO_TRANSPORTE { get; set; }
        public DbSet<TRANSPORTE> TRANSPORTE { get; set; }
        public DbSet<USUARIO> USUARIO { get; set; }
        public DbSet<VEHICULO> VEHICULO { get; set; }
        public DbSet<ZONA_TOUR> ZONA_TOUR { get; set; }
    
        public virtual int CREARDEPTO(Nullable<decimal> cANTIDADBANIOS, Nullable<decimal> cANTIDADDORMITORIOS, Nullable<decimal> pRECIO, string dIRECCION, Nullable<decimal> iD_CIUDAD, string dESCRIPCION, string cONDICIONESUSO, string hAVE_INTERNET, string hAVE_CALEFACCION, Nullable<decimal> pROM_MES_DIV, Nullable<decimal> pROM_MES_CONTRIB)
        {
            var cANTIDADBANIOSParameter = cANTIDADBANIOS.HasValue ?
                new ObjectParameter("CANTIDADBANIOS", cANTIDADBANIOS) :
                new ObjectParameter("CANTIDADBANIOS", typeof(decimal));
    
            var cANTIDADDORMITORIOSParameter = cANTIDADDORMITORIOS.HasValue ?
                new ObjectParameter("CANTIDADDORMITORIOS", cANTIDADDORMITORIOS) :
                new ObjectParameter("CANTIDADDORMITORIOS", typeof(decimal));
    
            var pRECIOParameter = pRECIO.HasValue ?
                new ObjectParameter("PRECIO", pRECIO) :
                new ObjectParameter("PRECIO", typeof(decimal));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var iD_CIUDADParameter = iD_CIUDAD.HasValue ?
                new ObjectParameter("ID_CIUDAD", iD_CIUDAD) :
                new ObjectParameter("ID_CIUDAD", typeof(decimal));
    
            var dESCRIPCIONParameter = dESCRIPCION != null ?
                new ObjectParameter("DESCRIPCION", dESCRIPCION) :
                new ObjectParameter("DESCRIPCION", typeof(string));
    
            var cONDICIONESUSOParameter = cONDICIONESUSO != null ?
                new ObjectParameter("CONDICIONESUSO", cONDICIONESUSO) :
                new ObjectParameter("CONDICIONESUSO", typeof(string));
    
            var hAVE_INTERNETParameter = hAVE_INTERNET != null ?
                new ObjectParameter("HAVE_INTERNET", hAVE_INTERNET) :
                new ObjectParameter("HAVE_INTERNET", typeof(string));
    
            var hAVE_CALEFACCIONParameter = hAVE_CALEFACCION != null ?
                new ObjectParameter("HAVE_CALEFACCION", hAVE_CALEFACCION) :
                new ObjectParameter("HAVE_CALEFACCION", typeof(string));
    
            var pROM_MES_DIVParameter = pROM_MES_DIV.HasValue ?
                new ObjectParameter("PROM_MES_DIV", pROM_MES_DIV) :
                new ObjectParameter("PROM_MES_DIV", typeof(decimal));
    
            var pROM_MES_CONTRIBParameter = pROM_MES_CONTRIB.HasValue ?
                new ObjectParameter("PROM_MES_CONTRIB", pROM_MES_CONTRIB) :
                new ObjectParameter("PROM_MES_CONTRIB", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREARDEPTO", cANTIDADBANIOSParameter, cANTIDADDORMITORIOSParameter, pRECIOParameter, dIRECCIONParameter, iD_CIUDADParameter, dESCRIPCIONParameter, cONDICIONESUSOParameter, hAVE_INTERNETParameter, hAVE_CALEFACCIONParameter, pROM_MES_DIVParameter, pROM_MES_CONTRIBParameter);
        }
    
        public virtual int CREARINVENTARIO(string nOMBRE_OBJ, Nullable<decimal> pRECIO_OBJ, string iMPORTANT, string sTATUS, Nullable<decimal> iDDEPTO)
        {
            var nOMBRE_OBJParameter = nOMBRE_OBJ != null ?
                new ObjectParameter("NOMBRE_OBJ", nOMBRE_OBJ) :
                new ObjectParameter("NOMBRE_OBJ", typeof(string));
    
            var pRECIO_OBJParameter = pRECIO_OBJ.HasValue ?
                new ObjectParameter("PRECIO_OBJ", pRECIO_OBJ) :
                new ObjectParameter("PRECIO_OBJ", typeof(decimal));
    
            var iMPORTANTParameter = iMPORTANT != null ?
                new ObjectParameter("IMPORTANT", iMPORTANT) :
                new ObjectParameter("IMPORTANT", typeof(string));
    
            var sTATUSParameter = sTATUS != null ?
                new ObjectParameter("STATUS", sTATUS) :
                new ObjectParameter("STATUS", typeof(string));
    
            var iDDEPTOParameter = iDDEPTO.HasValue ?
                new ObjectParameter("IDDEPTO", iDDEPTO) :
                new ObjectParameter("IDDEPTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREARINVENTARIO", nOMBRE_OBJParameter, pRECIO_OBJParameter, iMPORTANTParameter, sTATUSParameter, iDDEPTOParameter);
        }
    
        public virtual int CREARSERVICIOEXTRA(string nOMBRE, Nullable<decimal> pRECIO_ACT)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var pRECIO_ACTParameter = pRECIO_ACT.HasValue ?
                new ObjectParameter("PRECIO_ACT", pRECIO_ACT) :
                new ObjectParameter("PRECIO_ACT", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREARSERVICIOEXTRA", nOMBREParameter, pRECIO_ACTParameter);
        }
    
        public virtual int CREARUSUARIO(string dNI, string nOMBRE, string aPELLIDOS, string cORREO, string dIRECCION, Nullable<decimal> tELEFONO, string cONTRASENIA, Nullable<decimal> rOL_ID, string eXTRANJERO, string fRECUENTE)
        {
            var dNIParameter = dNI != null ?
                new ObjectParameter("DNI", dNI) :
                new ObjectParameter("DNI", typeof(string));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var aPELLIDOSParameter = aPELLIDOS != null ?
                new ObjectParameter("APELLIDOS", aPELLIDOS) :
                new ObjectParameter("APELLIDOS", typeof(string));
    
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            var dIRECCIONParameter = dIRECCION != null ?
                new ObjectParameter("DIRECCION", dIRECCION) :
                new ObjectParameter("DIRECCION", typeof(string));
    
            var tELEFONOParameter = tELEFONO.HasValue ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(decimal));
    
            var cONTRASENIAParameter = cONTRASENIA != null ?
                new ObjectParameter("CONTRASENIA", cONTRASENIA) :
                new ObjectParameter("CONTRASENIA", typeof(string));
    
            var rOL_IDParameter = rOL_ID.HasValue ?
                new ObjectParameter("ROL_ID", rOL_ID) :
                new ObjectParameter("ROL_ID", typeof(decimal));
    
            var eXTRANJEROParameter = eXTRANJERO != null ?
                new ObjectParameter("EXTRANJERO", eXTRANJERO) :
                new ObjectParameter("EXTRANJERO", typeof(string));
    
            var fRECUENTEParameter = fRECUENTE != null ?
                new ObjectParameter("FRECUENTE", fRECUENTE) :
                new ObjectParameter("FRECUENTE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CREARUSUARIO", dNIParameter, nOMBREParameter, aPELLIDOSParameter, cORREOParameter, dIRECCIONParameter, tELEFONOParameter, cONTRASENIAParameter, rOL_IDParameter, eXTRANJEROParameter, fRECUENTEParameter);
        }
    
        public virtual int ELIMINARDEPA(Nullable<decimal> n_ID)
        {
            var n_IDParameter = n_ID.HasValue ?
                new ObjectParameter("N_ID", n_ID) :
                new ObjectParameter("N_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINARDEPA", n_IDParameter);
        }
    
        public virtual int ELIMINARINVENTARIO(Nullable<decimal> n_ID)
        {
            var n_IDParameter = n_ID.HasValue ?
                new ObjectParameter("N_ID", n_ID) :
                new ObjectParameter("N_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINARINVENTARIO", n_IDParameter);
        }
    
        public virtual int MODIFICADEPARTAMENTO(Nullable<decimal> n_ID, Nullable<decimal> cANTIDADBANIOS, Nullable<decimal> cANTIDADDORMITORIOS, Nullable<decimal> pRECIO, string n_DIRECCION, Nullable<decimal> iD_CIUDAD, string n_DESCRIPCION, string cONDICIONESUSO, string hAVE_INTERNET, string hAVE_CALEFACCION, Nullable<decimal> pROM_MES_DIV, Nullable<decimal> pROM_MES_CONTRIB)
        {
            var n_IDParameter = n_ID.HasValue ?
                new ObjectParameter("N_ID", n_ID) :
                new ObjectParameter("N_ID", typeof(decimal));
    
            var cANTIDADBANIOSParameter = cANTIDADBANIOS.HasValue ?
                new ObjectParameter("CANTIDADBANIOS", cANTIDADBANIOS) :
                new ObjectParameter("CANTIDADBANIOS", typeof(decimal));
    
            var cANTIDADDORMITORIOSParameter = cANTIDADDORMITORIOS.HasValue ?
                new ObjectParameter("CANTIDADDORMITORIOS", cANTIDADDORMITORIOS) :
                new ObjectParameter("CANTIDADDORMITORIOS", typeof(decimal));
    
            var pRECIOParameter = pRECIO.HasValue ?
                new ObjectParameter("PRECIO", pRECIO) :
                new ObjectParameter("PRECIO", typeof(decimal));
    
            var n_DIRECCIONParameter = n_DIRECCION != null ?
                new ObjectParameter("N_DIRECCION", n_DIRECCION) :
                new ObjectParameter("N_DIRECCION", typeof(string));
    
            var iD_CIUDADParameter = iD_CIUDAD.HasValue ?
                new ObjectParameter("ID_CIUDAD", iD_CIUDAD) :
                new ObjectParameter("ID_CIUDAD", typeof(decimal));
    
            var n_DESCRIPCIONParameter = n_DESCRIPCION != null ?
                new ObjectParameter("N_DESCRIPCION", n_DESCRIPCION) :
                new ObjectParameter("N_DESCRIPCION", typeof(string));
    
            var cONDICIONESUSOParameter = cONDICIONESUSO != null ?
                new ObjectParameter("CONDICIONESUSO", cONDICIONESUSO) :
                new ObjectParameter("CONDICIONESUSO", typeof(string));
    
            var hAVE_INTERNETParameter = hAVE_INTERNET != null ?
                new ObjectParameter("HAVE_INTERNET", hAVE_INTERNET) :
                new ObjectParameter("HAVE_INTERNET", typeof(string));
    
            var hAVE_CALEFACCIONParameter = hAVE_CALEFACCION != null ?
                new ObjectParameter("HAVE_CALEFACCION", hAVE_CALEFACCION) :
                new ObjectParameter("HAVE_CALEFACCION", typeof(string));
    
            var pROM_MES_DIVParameter = pROM_MES_DIV.HasValue ?
                new ObjectParameter("PROM_MES_DIV", pROM_MES_DIV) :
                new ObjectParameter("PROM_MES_DIV", typeof(decimal));
    
            var pROM_MES_CONTRIBParameter = pROM_MES_CONTRIB.HasValue ?
                new ObjectParameter("PROM_MES_CONTRIB", pROM_MES_CONTRIB) :
                new ObjectParameter("PROM_MES_CONTRIB", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICADEPARTAMENTO", n_IDParameter, cANTIDADBANIOSParameter, cANTIDADDORMITORIOSParameter, pRECIOParameter, n_DIRECCIONParameter, iD_CIUDADParameter, n_DESCRIPCIONParameter, cONDICIONESUSOParameter, hAVE_INTERNETParameter, hAVE_CALEFACCIONParameter, pROM_MES_DIVParameter, pROM_MES_CONTRIBParameter);
        }
    
        public virtual int MODIFICARINVENTARIO(Nullable<decimal> n_ID, string nOMBRE_OBJ, Nullable<decimal> pRECIO_OBJ, string iMPORTANT, string sTATUS, Nullable<decimal> iDDEPTO)
        {
            var n_IDParameter = n_ID.HasValue ?
                new ObjectParameter("N_ID", n_ID) :
                new ObjectParameter("N_ID", typeof(decimal));
    
            var nOMBRE_OBJParameter = nOMBRE_OBJ != null ?
                new ObjectParameter("NOMBRE_OBJ", nOMBRE_OBJ) :
                new ObjectParameter("NOMBRE_OBJ", typeof(string));
    
            var pRECIO_OBJParameter = pRECIO_OBJ.HasValue ?
                new ObjectParameter("PRECIO_OBJ", pRECIO_OBJ) :
                new ObjectParameter("PRECIO_OBJ", typeof(decimal));
    
            var iMPORTANTParameter = iMPORTANT != null ?
                new ObjectParameter("IMPORTANT", iMPORTANT) :
                new ObjectParameter("IMPORTANT", typeof(string));
    
            var sTATUSParameter = sTATUS != null ?
                new ObjectParameter("STATUS", sTATUS) :
                new ObjectParameter("STATUS", typeof(string));
    
            var iDDEPTOParameter = iDDEPTO.HasValue ?
                new ObjectParameter("IDDEPTO", iDDEPTO) :
                new ObjectParameter("IDDEPTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICARINVENTARIO", n_IDParameter, nOMBRE_OBJParameter, pRECIO_OBJParameter, iMPORTANTParameter, sTATUSParameter, iDDEPTOParameter);
        }
    
        public virtual int MODIFICARSERVICIOEXTRA(Nullable<decimal> n_ID, string nOMBRE, Nullable<decimal> pRECIO_ACT)
        {
            var n_IDParameter = n_ID.HasValue ?
                new ObjectParameter("N_ID", n_ID) :
                new ObjectParameter("N_ID", typeof(decimal));
    
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var pRECIO_ACTParameter = pRECIO_ACT.HasValue ?
                new ObjectParameter("PRECIO_ACT", pRECIO_ACT) :
                new ObjectParameter("PRECIO_ACT", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICARSERVICIOEXTRA", n_IDParameter, nOMBREParameter, pRECIO_ACTParameter);
        }
    
        public virtual int MODIFICARUSUARIO(string dNI_USR, string n_NOMBRE, string n_APELLIDOS, string n_CORREO, string n_DIRECCION, Nullable<decimal> n_TELEFONO, Nullable<decimal> n_ROL_ID, string n_EXTRANJERO, string n_FRECUENTE)
        {
            var dNI_USRParameter = dNI_USR != null ?
                new ObjectParameter("DNI_USR", dNI_USR) :
                new ObjectParameter("DNI_USR", typeof(string));
    
            var n_NOMBREParameter = n_NOMBRE != null ?
                new ObjectParameter("N_NOMBRE", n_NOMBRE) :
                new ObjectParameter("N_NOMBRE", typeof(string));
    
            var n_APELLIDOSParameter = n_APELLIDOS != null ?
                new ObjectParameter("N_APELLIDOS", n_APELLIDOS) :
                new ObjectParameter("N_APELLIDOS", typeof(string));
    
            var n_CORREOParameter = n_CORREO != null ?
                new ObjectParameter("N_CORREO", n_CORREO) :
                new ObjectParameter("N_CORREO", typeof(string));
    
            var n_DIRECCIONParameter = n_DIRECCION != null ?
                new ObjectParameter("N_DIRECCION", n_DIRECCION) :
                new ObjectParameter("N_DIRECCION", typeof(string));
    
            var n_TELEFONOParameter = n_TELEFONO.HasValue ?
                new ObjectParameter("N_TELEFONO", n_TELEFONO) :
                new ObjectParameter("N_TELEFONO", typeof(decimal));
    
            var n_ROL_IDParameter = n_ROL_ID.HasValue ?
                new ObjectParameter("N_ROL_ID", n_ROL_ID) :
                new ObjectParameter("N_ROL_ID", typeof(decimal));
    
            var n_EXTRANJEROParameter = n_EXTRANJERO != null ?
                new ObjectParameter("N_EXTRANJERO", n_EXTRANJERO) :
                new ObjectParameter("N_EXTRANJERO", typeof(string));
    
            var n_FRECUENTEParameter = n_FRECUENTE != null ?
                new ObjectParameter("N_FRECUENTE", n_FRECUENTE) :
                new ObjectParameter("N_FRECUENTE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICARUSUARIO", dNI_USRParameter, n_NOMBREParameter, n_APELLIDOSParameter, n_CORREOParameter, n_DIRECCIONParameter, n_TELEFONOParameter, n_ROL_IDParameter, n_EXTRANJEROParameter, n_FRECUENTEParameter);
        }
    
        public virtual int ELIMINARUSUARIO(string uS_DNI)
        {
            var uS_DNIParameter = uS_DNI != null ?
                new ObjectParameter("US_DNI", uS_DNI) :
                new ObjectParameter("US_DNI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINARUSUARIO", uS_DNIParameter);
        }
    
        public virtual int ELIMINARSERVICIOEXTRA(Nullable<decimal> n_ID)
        {
            var n_IDParameter = n_ID.HasValue ?
                new ObjectParameter("N_ID", n_ID) :
                new ObjectParameter("N_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINARSERVICIOEXTRA", n_IDParameter);
        }
    }
}
