//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectorOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKLIST
    {
        public string ESTADO_ENTREGA { get; set; }
        public string ESTADO_DEVUELTO { get; set; }
        public string DESCRIPCION { get; set; }
        public string INVENTARIO_ID_INV { get; set; }
        public short RESERVA_ID_RESERVA { get; set; }
    
        public virtual INVENTARIO INVENTARIO { get; set; }
        public virtual RESERVA RESERVA { get; set; }
    }
}
