//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectorOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA_TRANSPORTE
    {
        public int PRECIO_CONTRATADO { get; set; }
        public short RESERVA_ID_RESERVA { get; set; }
        public short SERVICIO_TRANSPORTE_ID { get; set; }
    
        public virtual RESERVA RESERVA { get; set; }
        public virtual SERVICIO_TRANSPORTE SERVICIO_TRANSPORTE { get; set; }
    }
}
