//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectorOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANSPORTE
    {
        public System.DateTime FECHA { get; set; }
        public string CONDUCTOR_DNI { get; set; }
        public string VEHICULO_PATENTE { get; set; }
        public short SERVICIO_TRANSPORTE_ID { get; set; }
    
        public virtual CONDUCTOR CONDUCTOR { get; set; }
        public virtual SERVICIO_TRANSPORTE SERVICIO_TRANSPORTE { get; set; }
        public virtual VEHICULO VEHICULO { get; set; }
    }
}
