//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectorOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public USUARIO()
        {
            this.RESERVA = new HashSet<RESERVA>();
        }
    
        public string DNI { get; set; }
        public string NOMBRE { get; set; }
        public string APELLIDOS { get; set; }
        public string CORREO_ELECTRONICO { get; set; }
        public string DIRECCION { get; set; }
        public int TELEFONO { get; set; }
        public string CONTRASENIA { get; set; }
        public string ACTIVADO { get; set; }
        public short ROL_ID { get; set; }
        public string EXTRANJERO { get; set; }
        public string FRECUENTE { get; set; }
    
        public virtual ICollection<RESERVA> RESERVA { get; set; }
        public virtual ROL ROL { get; set; }
    }
}
