//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectorOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULO
    {
        public VEHICULO()
        {
            this.TRANSPORTE = new HashSet<TRANSPORTE>();
        }
    
        public string PATENTE { get; set; }
        public string COLOR { get; set; }
    
        public virtual ICollection<TRANSPORTE> TRANSPORTE { get; set; }
    }
}
