//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConectorOracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZONA_TOUR
    {
        public ZONA_TOUR()
        {
            this.SERVICIO_TOURS = new HashSet<SERVICIO_TOURS>();
        }
    
        public short ID_ZONA { get; set; }
        public string NOMBRE_ZONA { get; set; }
        public short CIUDAD_ID { get; set; }
    
        public virtual CIUDAD CIUDAD { get; set; }
        public virtual ICollection<SERVICIO_TOURS> SERVICIO_TOURS { get; set; }
    }
}
